---
# apache installation

- name: Add apache group
  group: name=www-data state=present

- name: Add apache user
  user: name=www-data comment="Apache2 user" createhome=no group=www-data shell=/bin/false state=present

- name: install apache packages
  apt: name={{ item }} state=present update-cache=yes cache_valid_time=3600
  with_items:
    - apache2
    - apache2-utils

- name: enable Apache2 mods
  apache2_module: name={{ item }} state=present
  with_items:
    - headers
    - expires
    - rewrite.load
    - ssl.load
  notify: restart apache2

- name: disable autoindex module in apache configuration
  apache2_module: name=autoindex state=absent
  notify: restart apache2

- name: disable default site
  command: a2dissite 000-default removes=/etc/apache2/sites-enabled/000-default.conf
  notify: restart apache2

- name: start and enable apache2 server
  service: name=apache2 state=started enabled=yes
