---

## Gitolite vars
gitolite_username: vagrant
gitolite_gitconfig_user_name: 'Git Service'
gitolite_gitconfig_user_email: "git@localhost.localdomain"
gitolite_gitconfig_push_default: current

## cgit vars
cgit_version: 0.11.2
cgit_title: "Vagrant Git Repository"
cgit_subtitle: "a web interface to {{ ansible_fqdn }} repositories"
